# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            DovDev
tagline:          'The code related musings of Yissachar Radcliffe'
description:      'The code related musings of Yissachar Radcliffe'
url:              http://dovdev.com/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars