# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        /:title

# Setup
title:            DovDev
tagline:          'The code related musings of Yissachar Radcliffe'
description:      'The code related musings of Yissachar Radcliffe'
url:              http://dovdev.com/

author:
  name:           'Yissachar Radcliffe'
  url:            https://dovdev.com/

paginate:         5

# Custom vars